"""
First step: https://docs.bokeh.org/en/latest/docs/first_steps.html
"""

import unittest

# pylint: skip-file


class TestFirstStep(unittest.TestCase):
  # simple line char plot
  def test_step_1(self) -> None:
    from bokeh.plotting import figure, show

    # prepare some data
    x = [1, 2, 3, 4, 5]
    y1 = [6, 7, 2, 4, 5]
    y2 = [2, 3, 4, 5, 6]
    y3 = [4, 5, 5, 7, 2]

    # create a new plot with a title and axis labels
    p = figure(title="Multiple line example",
               x_axis_label="x", y_axis_label="y")  # type: ignore[call-arg]

    # add multiple renderers
    p.line(x, y1, legend_label="Temp.", color="blue", line_width=2)
    p.line(x, y2, legend_label="Rate", color="red", line_width=2)
    p.line(x, y3, legend_label="Objects", color="green", line_width=2)

    # show the results
    show(p)

  # add and customize renderers

  def test_step_2(self) -> None:
    pass

  # add legends, text and annotations
  def test_step_3(self) -> None:
    pass

  # customize plot
  def test_step_4(self) -> None:
    pass

  # vectorize glyph properties
  def test_step_5(self) -> None:
    pass

  # combile plots
  def test_step_6(self) -> None:
    pass

  # display and export
  def test_step_7(self) -> None:
    pass

  # prodive and filter data
  def test_step_8(self) -> None:
    pass

  # use widgets
  def test_step_9(self) -> None:
    from bokeh.layouts import layout
    from bokeh.models import Div, RangeSlider, Spinner
    from bokeh.plotting import figure, show

    # prepare some data
    x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    y = [4, 5, 5, 7, 2, 6, 4, 9, 1, 3]

    # create plot with circle glyphs
    p = figure(x_range=(1, 9), width=500, height=250)  # type: ignore[arg-type]
    points = p.scatter(x=x, y=y, size=30, fill_color="#21a7df")

    # set up textarea (div): to display HTML text
    div = Div(
        text="""
              <p>Select the circle's size using this control element:</p>
              """,
        width=200,
        height=30,
    )

    # set up spinner: to select a numeric value
    spinner = Spinner(
        title="Circle size",  # a string to display above the widget
        low=0,  # the lowest possible number to pick
        high=60,  # the highest possible number to pick
        step=5,  # the increments by which the number can be adjusted
        value=points.glyph.size,  # the initial value to display in the widget
        width=200,  # the width of the widget in pixels
    )
    # link the value generated by the spinner to 'size' property of glyph
    spinner.js_link("value", points.glyph, "size")

    # set up RangeSlider: to adjust a range
    range_slider = RangeSlider(
        title="Adjust x-axis range",  # a title to display above the slider
        start=0,  # set the minimum value for the slider
        end=10,  # set the maximum value for the slider
        step=1,  # increments for the slider
        # initial values for slider,
        value=(p.x_range.start, p.x_range.end),  # type: ignore[attr-defined]
    )
    # link the value generated by range slider to existing plot, use attr_selector to select value from the tuple
    range_slider.js_link("value", p.x_range, "start", attr_selector=0)
    range_slider.js_link("value", p.x_range, "end", attr_selector=1)

    # create layout
    layout = layout(  # type: ignore[assignment]
        [
            [div, spinner],
            [range_slider],
            [p],
        ],
    )

    # show result
    show(layout)  # type: ignore[arg-type]
