options {
    STATIC = false;
}

// Expected output:
//The number is: 5551212
//The number is: 8885551212
PARSER_BEGIN(PhoneParser)
package com.spike.javacc.phone_lookahead;
import java.io.*;

public class PhoneParser {
    public static void main(String[] args) {
        parse("555-1212");
        parse("888-555-1212");
    }

    private static void parse(String input) {
        StringReader sr = new StringReader(input);
        PhoneParser p = new PhoneParser(sr);
        try {
            StringBuffer sb = p.PhoneNumber();
            System.out.println("The number is: " + sb);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
}
PARSER_END(PhoneParser)

TOKEN : {
    <FOUR_DIGITS : (<DIGITS>){4} >
    | <THREE_DIGITS : (<DIGITS>){3} >
    | <#DIGITS : ["0"-"9"] >
}

StringBuffer PhoneNumber() :
{
    StringBuffer number = new StringBuffer();
}
{
    // 预看
    (
    LOOKAHEAD(3)
    LocalNumber(number)
    | CountryNumber(number)
    )
    <EOF> { return number; }
}

void AreaCode(StringBuffer sb) :
{}
{
    <THREE_DIGITS> { sb.append(token.image); }
}

void LocalNumber(StringBuffer sb) :
{}
{
    AreaCode(sb)
    "-"
    <FOUR_DIGITS> { sb.append(token.image); }
}

void CountryNumber(StringBuffer sb) :
{}
{
    AreaCode(sb)
    "-"
    <THREE_DIGITS> { sb.append(token.image); }
    "-"
    <FOUR_DIGITS>  { sb.append(token.image); }
}