// Example 1.1. A simple grammar in 'Generating Parsers with JavaCC'
// 选项
options {
    JDK_VERSION = "1.8";
    LOOKAHEAD = 1;
}

// Expected output:
//Found a 'a'!
// 解析器类定义
PARSER_BEGIN(SimpleParser)
package com.spike.javacc.simple;
import java.io.*;

public class SimpleParser {
  public static void main(String [] args) throws ParseException {
    String someInput = "a";
    StringReader sr = new StringReader(someInput);
    Reader r = new BufferedReader(sr);
    SimpleParser parser = new SimpleParser(r);
    parser.A();
  }
}
PARSER_END(SimpleParser)

// 词法描述
TOKEN :
{
  < A : "a" >
}

// 句法描述
void A() :
{}
{
  < A >
  {
    System.out.println("Found a 'a'!");
  }
}